### ISSUE TITLE
total_reset -P doesn't work? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#251]
I get the error below, even though total_reset -R works fine, on my local alyx installation. I may be doing something wrong. 

```
$ python ./alyx/manage.py total_reset -P

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "alyx".
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "./alyx/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Miniconda3\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Miniconda3\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Miniconda3\lib\site-packages\django\core\management\base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Miniconda3\lib\site-packages\django\core\management\base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Nick\Documents\GitHub\alyx\alyx\misc\management\commands\total_reset.py", line 34, in handle
    call_command('reset_db', '-R alyx_ro')
  File "C:\Miniconda3\lib\site-packages\django\core\management\__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "C:\Miniconda3\lib\site-packages\django\core\management\base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Nick\Documents\GitHub\alyx\alyx\misc\management\commands\reset_db.py", line 98, in handle
    cursor.execute(create_query)
psycopg2.ProgrammingError: role "alyx_ro" does not exist
```

**Comment by nippoo** [comment]
It's not designed to work on your local installation. It'll only work if you have the alyx_ro installation (and will also fail later if you're not running apache2). The -P flag stands for "production" ie when you're running it in production not as a local dev copy...

**Comment by nsteinme** [comment]
I see, thanks, I didn't understand that.
