### ISSUE TITLE
New static dump

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#264]
@nsteinme could you do a new static dump? I think you should have the command somewhere, I guess we should add it to the manage.py commands. Ideally the dump should have all the user emails, and the stock managers as well (charu and laura).

**Comment by nsteinme** [comment]
Hi Cyrille, see cone:/var/www/tempdata/static_dump_20170501.json, which was
made with this command:

python /var/www/alyx/alyx/manage.py dumpdata auth.user subjects.species
subjects.source equipment.lablocation actions.proceduretype --indent 2
--exclude contenttypes > /var/www/tempdata/static_dump_20170501.json

When you say it should "have the stock managers as well", what does that
mean? I guess it has to do with the new StockManager model, but I don't see
an "auth.stockmanager" or anything in the list of tables? So I'm not quite
sure what to do about this, let me know.

I guess we will not do this dump again after the final import from sheets
so it is probably not totally critical to incorporate it into manage.py if
it's a pain.

**Comment by rossant** [comment]
I think you have to:

* go to alyx-dev and merge the better-users branch (PR in progress)
* Add the StockManagers (charu and laura?), which you should find in the IT section of the alyx admin home page
* Update the dump command to add `subjects.stockmanager` (I think)
* Make a new dump

Once it works on alyx-dev we can merge the PR and update both alyx and alyx-dev on master.

**Comment by nsteinme** [comment]
Uh, hm, I think I broke something. On alyx-dev I tried: 

```
git pull
git checkout -b better-users origin/better-users
git merge master
python ./alyx/manage.py total_reset -R -P
```

but got this error:

```
...
Loading '/var/www/alyx-dev/alyx/misc/management/commands/../../../../data/json/09-surgery' fixtures...
Checking '/var/www/alyx-dev/alyx/misc/management/commands/../../../../data/json' for fixtures...
Installing json fixture '09-surgery' from '/var/www/alyx-dev/alyx/misc/management/commands/../../../../data/json'.
Traceback (most recent call last):
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column actions_surgery_users.ordereduser_id does not exist
LINE 1: ...IN "actions_surgery_users" ON ("auth_user"."id" = "actions_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./alyx/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx-dev/alyx/misc/management/commands/total_reset.py", line 47, in handle
    call_command('download_gsheets', options.get('data_dir'), '-R')
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx-dev/alyx/misc/management/commands/download_gsheets.py", line 686, in handle
    call_command('loaddata', fullpath, verbosity=3, interactive=False)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
    obj.save(using=self.using)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/serializers/base.py", line 208, in save
    getattr(self.object, accessor_name).set(object_list)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 990, in set
    old_ids = set(self.using(db).values_list(self.target_field.target_field.attname, flat=True))
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/models/query.py", line 152, in __iter__
    for row in compiler.results_iter():
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 828, in results_iter
    results = self.execute_sql(MULTI)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/var/www/alyx-dev/alyx/misc/management/commands/../../../../data/json/09-surgery.json': Could not load actions.Surgery(pk=da454001-8fab-4386-9bd0-28f8a70f3c2b): column actions_surgery_users.ordereduser_id does not exist
LINE 1: ...IN "actions_surgery_users" ON ("auth_user"."id" = "actions_s...
```

So to figure out whether that was because of the WIP, I tried:

```
git checkout master
python ./alyx/manage.py total_reset -R -P

```
but then I got this error: 

```
10:46:50 [INFO] Executing... "DROP SCHEMA public CASCADE;"
10:46:50 [INFO] Executing... "CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO public;GRANT ALL ON SCHEMA public TO alyx_dev; GRANT USAGE ON SCHEMA public TO  alyx_ro;GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO  alyx_ro;GRANT SELECT ON ALL TABLES IN SCHEMA public TO  alyx_ro;"
Reset successful!
Traceback (most recent call last):
  File "./alyx/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx-dev/alyx/misc/management/commands/total_reset.py", line 42, in handle
    call_command('migrate')
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/loader.py", line 244, in build_graph
    self.graph.validate_consistency()
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/graph.py", line 261, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/graph.py", line 261, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/var/www/alyx/alyx/lib/python3.5/site-packages/django/db/migrations/graph.py", line 104, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration imaging.0001_initial dependencies reference nonexistent parent node ('actions', '0001_initial')

```

**Comment by rossant** [comment]
You have to make migrate first I think

**Comment by nsteinme** [comment]
Ok, I'm super confused about why that worked, since the things you see on
the screen when you do "make migrate" appear to be the same as the first
things you see when you do "manage.py total_reset", but in any case after I
did make migrate the total reset did work!

So you can find a static dump at /var/www/tempdata with the
subjects.stockmanager entries for laura and charu. It was made with this
command:

python /var/www/alyx-dev/alyx/manage.py dumpdata auth.user subjects.species
subjects.source equipment.lablocation actions.proceduretype
subjects.stockmanager --indent 2 --exclude contenttypes >
/var/www/tempdata/static_dump_20170501.json

**Comment by rossant** [comment]
thanks!
