### ISSUE TITLE
Migrations fail during fresh installation on Linux

### ISSUE THREAD

**Issue by brykko** [cortex-lab/alyx#384]
I just tried to set up a fresh local installation of alyx on Ubuntu 16.04, with the following steps

- Create a new postgresql database
- Set up and activate new python3 virtualenv
- Clone current alyx version
- Run pip installation <pre><code>(alyx_new_test) brick@brickbook-II:~/Documents/prog/python/alyx_new_test$ sudo ./bin/pip3 install -r ./alyx/requirements.txt</code>
- Update the settings_secret.py file with the database info

Now I attempt to do the migrations, and I get this error:

```
(alyx_new_test) brick@brickbook-II:~/Documents/prog/python/alyx_new_test$ sudo ./bin/python3 ./alyx/alyx/manage.py migrate
Operations to perform:
  Apply all migrations: actions, admin, auth, authtoken, behavior, contenttypes, data, electrophysiology, equipment, imaging, misc, reversion, sessions, subjects
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying misc.0001_initial... OK
  Applying equipment.0001_initial... OK
  Applying subjects.0001_initial...Traceback (most recent call last):
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column subjects_source.description does not exist
LINE 1: ...ubjects_source"."json", "subjects_source"."name", "subjects_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./alyx/alyx/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 86, in database_forwards
    field,
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 414, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 154, in column_sql
    default_value = self.effective_default(field)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 206, in effective_default
    default = field.get_default()
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/models/fields/related.py", line 952, in get_default
    field_default = super(ForeignKey, self).get_default()
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 778, in get_default
    return self._get_default()
  File "/home/brick/Documents/prog/python/alyx_new_test/alyx/alyx/subjects/models.py", line 64, in _default_source
    if s:
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/models/query.py", line 254, in __bool__
    self._fetch_all()
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/brick/Documents/prog/python/alyx_new_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column subjects_source.description does not exist
LINE 1: ...ubjects_source"."json", "subjects_source"."name", "subjects_...

```

**Comment by rossant** [comment]
Getting migrations to work on multiapp django projects is notoriously painful...
Maybe you could try to delete all migrations and start from scratch, see the [Makefile](https://github.com/cortex-lab/alyx/blob/master/alyx/Makefile#L18)

**Comment by brykko** [comment]
Thanks for the advice – running "make rmmigrations migrate" solved the problem. The tests also run without errors.

However, after starting the server, we still experience an issue we encountered previously (#355) when viewing the "subjects" page. I'll post further information on the original issue page.
