### ISSUE TITLE
psycopg2.errors.UndefinedColumn: column misc_labmember.is_public_user does not exist

### ISSUE THREAD

**Issue by dervinism** [cortex-lab/alyx#733]
After running python setup.py I get the following error:

Database successfully created
Configuration files successfully created from templates
Traceback (most recent call last):
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column misc_labmember.is_public_user does not exist
LINE 1: ...ember"."id", "misc_labmember"."is_stock_manager", "misc_labm...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "alyx/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 248, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 131, in apply
    operation.database_forwards(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 599, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 345, in column_sql
    " ".join(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 296, in _iter_column_sql
    default_value = self.effective_default(field)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 410, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 388, in _effective_default
    default = field.get_default()
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1111, in get_default
    field_default = super().get_default()
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 918, in get_default
    return self._get_default()
  File "/var/www/alyx-main/alyx/alyx/subjects/models.py", line 103, in default_responsible
    return get_user_model().objects.order_by('-is_stock_manager').first()
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/query.py", line 753, in first
    for obj in (self if self.ordered else self.order_by("pk"))[:1]:
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column misc_labmember.is_public_user does not exist
LINE 1: ...ember"."id", "misc_labmember"."is_stock_manager", "misc_labm...
                                                             ^

Traceback (most recent call last):
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "is_public_user" of relation "misc_labmember" does not exist
LINE 1: ...active", "date_joined", "id", "is_stock_manager", "is_public...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "alyx/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 1, in <module>
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 171, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 154, in _create_user
    user.save(using=self._db)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/alyx-main/alyx/alyxvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "is_public_user" of relation "misc_labmember" does not exist
LINE 1: ...active", "date_joined", "id", "is_stock_manager", "is_public...
                                                             ^

Database successfully configured for Alyx
------------------------
Alyx setup successful <3

**Comment by rossant** [comment]
@k1o0 @oliche @juhuntenburg do you have any idea why this error occurs?

**Comment by dervinism** [comment]
I've got exactly the same error after attempting to install on a different computer. Do you have any idea about the cause of this issue? Any help would really be much appreciated as I am stuck on this issue for days now.

**Comment by dervinism** [comment]
The operating system is Ubuntu 20.04.4 LTS. All other instructions are followed as described with an extra step of renaming /var/www/alyx-main/alyx/alyx/alyx/settings_ci.py to /var/www/alyx-main/alyx/alyx/alyx/settings.py as described in https://github.com/cortex-lab/alyx/issues/717

**Comment by dervinism** [comment]
Also fails on Ubuntu 18.04.6 LTS with the same error.

**Comment by dervinism** [comment]
Switching to older commit like 09ff14a497d38718ebe8d2801ebbb1abcf0ba4fe fixed this error.
